# Generated by Django 3.2.5 on 2021-08-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0005_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='', upload_to='Blogapp/images'),
            preserve_default=False,
        ),
    ]
